// <auto-generated />
namespace SimpleWebApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDbConfandAuthorization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDbConfandAuthorization));
        
        string IMigrationMetadata.Id
        {
            get { return "201606091044514_Add Db Conf and Authorization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
